### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by ebrehault** [makinacorpus/ngx-schema-form#205]
Hi all!

I have created a branch https://github.com/makinacorpus/ngx-schema-form/tree/2.0.x to create the Angular6+ version.

I have used the default library setup offered by Angular CLI 6, and I took the opportunity to change the name of the package (=> ngx-schema-form).

Opinions?

**Comment by sunew** [comment]
Fine!

**Comment by gpessa** [comment]
Are we gonna merge this?

**Comment by ebrehault** [comment]
I plan to.

**Comment by ebrehault** [comment]
FYI, I made another branch (https://github.com/makinacorpus/ngx-schema-form/tree/ng6) which preserves the git history.

That's the one I will merge.
