### ISSUE TITLE
angular 6 build fails 

### ISSUE THREAD

**Issue by jmsegrev** [makinacorpus/ngx-schema-form#210]
I installed 2.0.0-beta.2 in a brand new ng 6 generated project, after following the "getting started", the build failed with the following error.
```
ERROR in Cannot read property 'members' of undefined
```
Also when the build is run with --aot, it fails with:
```
ERROR in : Invalid provider for WidgetRegistry in /home/jmsegrev/Workspace/cloudgeex/wol-client/wolverine-frontend/node_modules/ngx-schema-form/ngx-schema-form.d.ts. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.
```

**Comment by monalisasaha79** [comment]
Is there any update on this??
I am getting following error
[23:31:27]  typescript error 
            Invalid provider for WidgetRegistry in 
            /Users/arindamsaha76/Desktop/Arindam/urbbit-client/node_modules/ngx-schema-form/ngx-schema-form.d.ts. 
            useClass cannot be undefined. Usually it happens when: 1. There's a circular dependency (might be caused by 
            using index.ts (barrel) files). 2. Class was used before it was declared. Use forwardRef in this case. 

Error: The Angular AoT build failed. See the issues above
    at /Users/arindamsaha76/Desktop/Arindam/urbbit-client/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/arindamsaha76/Desktop/Arindam/urbbit-client/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/arindamsaha76/Desktop/Arindam/urbbit-client/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/arindamsaha76/Desktop/Arindam/urbbit-client/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)

**Comment by ebrehault** [comment]
I'll try to work on that this weekend, but if anybody wants to provide a fix, PR welcome :)
