### ISSUE TITLE
[Feature] Template generated schema

### ISSUE THREAD

**Issue by jmsegrev** [makinacorpus/ngx-schema-form#212]
I've been using **ngx-schema-form** to replace all forms in an application with a massive amount of them. While working on this, I've realized that the verbosity of defining the forms inside the components with a JSON schema, even though awesome, is not the cleanest, nor the Angular way. For my use case, generating the schema from the template, would be a better approach and a nice feature to have.

One of my team members will be working on our solution for this. It could be implemented either as a external package or as part of the core, I was wandering your thoughts on this, if any?

The idea is simple, an alternative way of writing the JSON schema, having some components that would be used to generate the form definition.

The result usage would be something on the lines of the following html: 
```html
<sf-form [(model)]="model">

  <sf-field name="company" format="string" [required]="true">Company</sf-field>

  <sf-fieldset id="color-picker" title="Favorite Color">
    <sf-field name="colors" type="array">
      <sf-field name="name" format="string" [required]="true">
        Name
      </sf-field>
      <sf-field name="name" widget="color | {}" [required]="true">
        Color 
      </sf-field>
      <sf-button>Add</sf-button>
    </sf-field>
  </sf-fieldset>

  <sf-fieldset title="Signin">
    <sf-field name="credentials" type="object">
      <sf-field name="password" format="password" [validators]="local_fn | [local_fn, ...]" [required]="true">
        Password
      </sf-field>
      <sf-field name="passwordConfirm" format="password" [validators]="local_fn | [local_fn, ...]" [required]="true">
        Confirm
      </sf-field>
    </sf-field>
  </sf-fieldset>

  <sf-button (click)="signin()">Signin</sf-button>

</sf-form>

```

**Comment by WhileTrueEndWhile** [comment]
I hope the best for this proposal. However, I would like to mention the following alternatives:

- You could generate a schema from a JSON instance (http://json-schema.org/implementations.html#from-data)

- You could preprocess the JSON schema (YAML, JSON with comments) to make it clearer... (I prefer dot notation to deep objects)

I would disconnect the JSON schema from the component and receive it through a service... (I like that the components know as little about the model as possible and only change it in exceptions themselves)

**Comment by ebrehault** [comment]
The original underlying idea of ngx-schema-form is the form schema is unknown at the time we are developping the app (it is sent by a backend, or maybe computed dynamically at runtime).

What you propose is kind of close to what `@angular/forms` does. But I guess it could make sense and can be very useful in many cases.

I guess that's fine to put it in core, but in case it makes the bundle bigger, maybe it could be in specific NgModule, so people can import this extra module only if they need it.

**Comment by WhileTrueEndWhile** [comment]
Ok, so the new approach would be to read meta information from HTML (possibly at runtime) for "known data types" to build a schema. I would then absolutely perform this process at build time.
In this way, features such as the generation of type script definitions from the schema can also be used (See [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript)).
