### ISSUE TITLE
Multi column form

### ISSUE THREAD

**Issue by AviFix** [makinacorpus/ngx-schema-form#219]
Hi

Is it possible to layout the form fields horizontally instead of vertically

Like this
![image](https://user-images.githubusercontent.com/3835504/42097409-c3033ccc-7bc0-11e8-9f18-ac765854602d.png)

And not like this
![image](https://user-images.githubusercontent.com/3835504/42097462-dbc4cb68-7bc0-11e8-9b50-61202dc52d08.png)

Thanks

**Comment by WhileTrueEndWhile** [comment]
I do this by using my own template for objects/fieldsets _(1)_ and then adjusting the width with CSS.
It occurs to me that it might be even cooler to simply pass a CSS class (e.g. `col-md-6`) from the schema into HTML.


----


_(1)_ See:

- https://github.com/makinacorpus/ngx-schema-form#user-content-creating-a-custom-widget
- https://github.com/makinacorpus/ngx-schema-form/blob/master/projects/schema-form/src/lib/defaultwidgets/object/object.widget.ts
- `this.schema.widget`

**Comment by AviFix** [comment]
Thanks for the advice
That seems to do the trick

**Comment by aaronhong** [comment]
> It occurs to me that it might be even cooler to simply pass a CSS class (e.g. col-md-6) from the schema into HTML.
@WhileTrueEndWhile how do you do this? I tried looking at the linked issues.

**Comment by WhileTrueEndWhile** [comment]
You have to create your own custom widget registry. You could start by copying existing widgets. Then you can modify the templates and insert your CSS class from proprietary schema properties.
